// apps/console/src/routes/routes.tsx
import { createFileRoute } from "@tanstack/react-router";
import {
  Card,
  Chip,
  ProgressBar,
  Spinner,
  Table,
} from "@heroui/react";
import { useRoutingHealth } from "../hooks/use-queries";

export const Route = createFileRoute("/routes")({
  component: RoutesPage,
});

function RoutesPage() {
  const health = useRoutingHealth();

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold">Routes Health</h1>

      {health.isLoading ? (
        <div className="flex justify-center py-20">
          <Spinner size="lg" />
        </div>
      ) : health.data ? (
        <>
          <Card.Root>
            <Card.Header>
              <h2 className="text-lg font-semibold">Circuit Breaker Config</h2>
            </Card.Header>
            <Card.Content>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                <div>
                  <span className="text-default-400">Threshold</span>
                  <p className="font-semibold">
                    {health.data.config.circuitBreakerPolicy.threshold}
                  </p>
                </div>
                <div>
                  <span className="text-default-400">Cooldown</span>
                  <p className="font-semibold">
                    {health.data.config.circuitBreakerPolicy.cooldownMs}ms
                  </p>
                </div>
                <div>
                  <span className="text-default-400">Persistent</span>
                  <p className="font-semibold">
                    {health.data.config.persistentBackend ? "Yes" : "No"}
                  </p>
                </div>
                <div>
                  <span className="text-default-400">Targets</span>
                  <p className="font-semibold">
                    {Object.keys(health.data.targets).length}
                  </p>
                </div>
              </div>
            </Card.Content>
          </Card.Root>

          <Card.Root>
            <Card.Content className="p-0">
              <Table.Root aria-label="Routes health">
                <Table.Header>
                  <Table.Column isRowHeader>Route</Table.Column>
                  <Table.Column>Status</Table.Column>
                  <Table.Column>Strategy</Table.Column>
                  <Table.Column>Targets</Table.Column>
                  <Table.Column>Healthy</Table.Column>
                  <Table.Column>Error Rate</Table.Column>
                </Table.Header>
                <Table.Body>
                  {Object.entries(health.data.routes).map(
                    ([route, info]) => {
                      const targetMetrics = info.targets
                        .map((t) => health.data.targets[t])
                        .filter(Boolean);
                      const avgErrorRate =
                        targetMetrics.length > 0
                          ? targetMetrics.reduce(
                              (a, t) => a + t.metrics.errorRate,
                              0
                            ) / targetMetrics.length
                          : 0;

                      return (
                        <Table.Row key={route}>
                          <Table.Cell className="font-mono text-sm">
                            {route}
                          </Table.Cell>
                          <Table.Cell>
                            <HealthChip status={info.healthStatus} />
                          </Table.Cell>
                          <Table.Cell className="text-sm">
                            {info.strategy}
                          </Table.Cell>
                          <Table.Cell className="text-sm">
                            {info.targets.join(", ")}
                          </Table.Cell>
                          <Table.Cell>
                            {info.healthyTargetCount}/{info.totalTargetCount}
                          </Table.Cell>
                          <Table.Cell>
                            <ProgressBar.Root
                              value={avgErrorRate * 100}
                              color={
                                avgErrorRate > 0.5
                                  ? "danger"
                                  : avgErrorRate > 0.2
                                    ? "warning"
                                    : "success"
                              }
                              className="w-24"
                            />
                          </Table.Cell>
                        </Table.Row>
                      );
                    }
                  )}
                </Table.Body>
              </Table.Root>
            </Card.Content>
          </Card.Root>

          <Card.Root>
            <Card.Header>
              <h2 className="text-lg font-semibold">Targets</h2>
            </Card.Header>
            <Card.Content className="p-0">
              <Table.Root aria-label="Target details">
                <Table.Header>
                  <Table.Column isRowHeader>Target</Table.Column>
                  <Table.Column>Error Rate</Table.Column>
                  <Table.Column>Recovery Score</Table.Column>
                  <Table.Column>Latency</Table.Column>
                </Table.Header>
                <Table.Body>
                  {Object.entries(health.data.targets).map(
                    ([target, info]) => (
                      <Table.Row key={target}>
                        <Table.Cell className="font-mono text-sm">
                          {target}
                        </Table.Cell>
                        <Table.Cell>
                          <Chip
                            size="sm"
                            variant="soft"
                            color={
                              info.metrics.errorRate > 0.5
                                ? "danger"
                                : info.metrics.errorRate > 0.2
                                  ? "warning"
                                  : "success"
                            }
                          >
                            {(info.metrics.errorRate * 100).toFixed(1)}%
                          </Chip>
                        </Table.Cell>
                        <Table.Cell>
                          <ProgressBar.Root
                            value={info.metrics.recoveryScore * 100}
                            className="w-24"
                          />
                        </Table.Cell>
                        <Table.Cell className="text-sm">
                          {info.metrics.freshness.latencyFreshMs != null
                            ? `${info.metrics.freshness.latencyFreshMs}ms`
                            : "—"}
                        </Table.Cell>
                      </Table.Row>
                    )
                  )}
                </Table.Body>
              </Table.Root>
            </Card.Content>
          </Card.Root>
        </>
      ) : (
        <p className="text-danger">{String(health.error)}</p>
      )}
    </div>
  );
}

function HealthChip({
  status,
}: {
  status: "healthy" | "degraded" | "down";
}) {
  const color = { healthy: "success", degraded: "warning", down: "danger" }[
    status
  ] as "success" | "warning" | "danger";
  return (
    <Chip size="sm" variant="soft" color={color}>
      {status}
    </Chip>
  );
}

// apps/dashboard/src/routes/routes/+page.svelte
<script lang="ts">
  import * as Card from "$lib/components/ui/card";
  import * as Table from "$lib/components/ui/table";
  import * as Breadcrumb from "$lib/components/ui/breadcrumb";
  import { Badge } from "$lib/components/ui/badge";
  import type { RoutingHealthResponse } from "$lib/api.js";

  let { data } = $props<{
    data: { routingHealth: RoutingHealthResponse | null };
  }>();

  function stateLabel(state: Record<string, unknown>): string {
    if (typeof state === "string") return state;
    if (state && "state" in state) return String(state.state);
    return "unknown";
  }
  function stateDotColor(state: string): string {
    if (state === "closed") return "bg-success";
    if (state === "open") return "bg-destructive";
    return "bg-warning";
  }
  function healthDot(status: string): string {
    if (status === "healthy") return "bg-success";
    if (status === "degraded") return "bg-warning";
    return "bg-destructive";
  }
</script>

<Breadcrumb.Root>
  <Breadcrumb.List>
    <Breadcrumb.Item>
      <Breadcrumb.Page>Routes</Breadcrumb.Page>
    </Breadcrumb.Item>
  </Breadcrumb.List>
</Breadcrumb.Root>

<div class="mb-3 mt-1">
  <h1 class="text-xl font-semibold tracking-tight">Routing Health</h1>
  <p class="text-xs text-muted-foreground">Circuit breaker and target availability</p>
</div>

{#if data.routingHealth}
  <div class="mb-4 grid grid-cols-2 md:grid-cols-4 gap-2">
    <Card.Root>
      <Card.Content>
        <p class="text-[11px] text-muted-foreground uppercase tracking-wider font-medium">Total</p>
        <p class="text-2xl font-bold tracking-tight">{Object.keys(data.routingHealth.routes).length}</p>
      </Card.Content>
    </Card.Root>
    <Card.Root class="border-t-2 border-t-success">
      <Card.Content>
        <p class="text-[11px] text-muted-foreground uppercase tracking-wider font-medium">Healthy</p>
        <p class="text-2xl font-bold tracking-tight text-success">
          {Object.values(data.routingHealth.routes).filter(
            (r) => r.healthStatus === "healthy"
          ).length}
        </p>
      </Card.Content>
    </Card.Root>
    <Card.Root class="border-t-2 border-t-warning">
      <Card.Content>
        <p class="text-[11px] text-muted-foreground uppercase tracking-wider font-medium">Degraded</p>
        <p class="text-2xl font-bold tracking-tight text-warning">
          {Object.values(data.routingHealth.routes).filter(
            (r) => r.healthStatus === "degraded"
          ).length}
        </p>
      </Card.Content>
    </Card.Root>
    <Card.Root class="border-t-2 border-t-destructive">
      <Card.Content>
        <p class="text-[11px] text-muted-foreground uppercase tracking-wider font-medium">Down</p>
        <p class="text-2xl font-bold tracking-tight text-destructive">
          {Object.values(data.routingHealth.routes).filter(
            (r) => r.healthStatus === "down"
          ).length}
        </p>
      </Card.Content>
    </Card.Root>
  </div>

  {#if data.routingHealth.config}
    <Card.Root class="mb-4">
      <Card.Header>
        <Card.Title class="text-[11px] text-muted-foreground uppercase tracking-wider font-medium">Circuit Breaker Policy</Card.Title>
      </Card.Header>
      <Card.Content>
        <div class="grid grid-cols-2 md:grid-cols-4 gap-3">
          <div>
            <p class="text-[10px] text-muted-foreground">Threshold</p>
            <p class="text-sm font-medium">{data.routingHealth.config.circuitBreakerPolicy.threshold} failures</p>
          </div>
          <div>
            <p class="text-[10px] text-muted-foreground">Cooldown</p>
            <p class="text-sm font-medium">
              {(
                data.routingHealth.config.circuitBreakerPolicy.cooldownMs / 1000
              ).toFixed(0)}s
            </p>
          </div>
          {#if data.routingHealth.config.circuitBreakerPolicy.errorRateWindowMs}
            <div>
              <p class="text-[10px] text-muted-foreground">Error Rate Window</p>
              <p class="text-sm font-medium">
                {(
                  data.routingHealth.config.circuitBreakerPolicy
                    .errorRateWindowMs / 1000
                ).toFixed(0)}s
              </p>
            </div>
          {/if}
          {#if data.routingHealth.config.circuitBreakerPolicy.errorRateThreshold != null}
            <div>
              <p class="text-[10px] text-muted-foreground">Error Rate Threshold</p>
              <p class="text-sm font-medium">
                {(
                  data.routingHealth.config.circuitBreakerPolicy
                    .errorRateThreshold * 100
                ).toFixed(0)}%
              </p>
            </div>
          {/if}
          <div>
            <p class="text-[10px] text-muted-foreground">Backend</p>
            <p class="text-sm font-medium">
              {data.routingHealth.config.persistentBackend
                ? "Persistent (DO)"
                : "In-memory"}
            </p>
          </div>
        </div>
      </Card.Content>
    </Card.Root>
  {/if}

  <div class="mb-4">
    <p class="text-[11px] text-muted-foreground uppercase tracking-wider font-medium mb-2">Routes</p>
    <Table.Root>
      <Table.Header>
        <Table.Row>
          <Table.Head>Route</Table.Head>
          <Table.Head>Health</Table.Head>
          <Table.Head>Targets</Table.Head>
          <Table.Head>Strategy</Table.Head>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {#each Object.entries(data.routingHealth.routes) as [name, route]}
          <Table.Row>
            <Table.Cell class="font-mono text-xs font-medium">{name}</Table.Cell>
            <Table.Cell>
              <Badge variant="secondary">
                <span class="inline-block size-2 rounded-full {healthDot(route.healthStatus)}"></span>
                {route.healthStatus}
              </Badge>
            </Table.Cell>
            <Table.Cell class="text-xs"
              >{route.healthyTargetCount}/{route.totalTargetCount}
              {#if route.totalTargetCount > 0}<span class="text-muted-foreground"
                  >({(
                    (route.healthyTargetCount / route.totalTargetCount) *
                    100
                  ).toFixed(0)}%)</span
                >{/if}</Table.Cell
            >
            <Table.Cell class="text-xs text-muted-foreground"
              >{route.strategy ?? "default"}</Table.Cell
            >
          </Table.Row>
        {/each}
      </Table.Body>
    </Table.Root>
  </div>

  {#if data.routingHealth.targets && Object.keys(data.routingHealth.targets).length > 0}
    <div>
      <p class="text-[11px] text-muted-foreground uppercase tracking-wider font-medium mb-2">Target Details</p>
      <Table.Root>
        <Table.Header>
          <Table.Row>
            <Table.Head>Target</Table.Head>
            <Table.Head>Circuit</Table.Head>
            <Table.Head>Error Rate</Table.Head>
            <Table.Head>Recovery</Table.Head>
            <Table.Head>Freshness</Table.Head>
          </Table.Row>
        </Table.Header>
        <Table.Body>
          {#each Object.entries(data.routingHealth.targets) as [name, target]}
            {@const state = stateLabel(target.circuitState)}
            <Table.Row>
              <Table.Cell class="font-mono text-xs">{name}</Table.Cell>
              <Table.Cell>
                <Badge variant="secondary">
                  <span class="inline-block size-2 rounded-full {stateDotColor(state)}"></span>
                  {state}
                </Badge>
              </Table.Cell>
              <Table.Cell class="text-xs"
                >{#if target.metrics?.errorRate != null}<span
                    class={target.metrics.errorRate > 0.1
                      ? "text-destructive"
                      : target.metrics.errorRate > 0.01
                        ? "text-warning"
                        : "text-success"}
                    >{(target.metrics.errorRate * 100).toFixed(1)}%</span
                  >{:else}<span class="text-muted-foreground">-</span
                  >{/if}</Table.Cell
              >
              <Table.Cell class="text-xs"
                >{#if target.metrics?.recoveryScore != null}{(
                    target.metrics.recoveryScore * 100
                  ).toFixed(0)}%{:else}<span class="text-muted-foreground"
                    >-</span
                  >{/if}</Table.Cell
              >
              <Table.Cell class="text-xs text-muted-foreground"
                >{#if target.metrics?.freshness}lat: {target.metrics.freshness
                    .latencyFreshMs ?? "-"}ms / fail: {target.metrics.freshness
                    .failureFreshMs ?? "-"}ms{:else}-{/if}</Table.Cell
              >
            </Table.Row>
          {/each}
        </Table.Body>
      </Table.Root>
    </div>
  {/if}
{:else}
  <Card.Root class="py-4 text-center">
    <Card.Content>
      <p class="text-sm text-muted-foreground">Failed to load routing health.</p>
    </Card.Content>
  </Card.Root>
{/if}
