// apps/dashboard/src/routes/config/accounts/+page.svelte
<script lang="ts">
  import { createClient, getStoredCredentials } from "$lib/auth.js";
  import * as Breadcrumb from "$lib/components/ui/breadcrumb";
  import * as Card from "$lib/components/ui/card";
  import * as Table from "$lib/components/ui/table";
  import { Button } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";
  import { Label } from "$lib/components/ui/label";
  import { Badge } from "$lib/components/ui/badge";
  import { Switch } from "$lib/components/ui/switch";
  import Plus from "@lucide/svelte/icons/plus";
  import Save from "@lucide/svelte/icons/save";
  import Pencil from "@lucide/svelte/icons/pencil";
  import Trash2 from "@lucide/svelte/icons/trash-2";

  type Account = {
    email: string;
    role: string;
    enabled: boolean;
    createdAt: number;
  };
  type AccountsConfig = { accounts: Account[] };

  let loading = $state(true);
  let saving = $state(false);
  let error = $state("");
  let success = $state("");
  let editAccountEmail = $state<string | null>(null);
  let showCreateForm = $state(false);
  let accounts = $state<Account[]>([]);
  let formEmail = $state("");
  let formRole = $state("viewer");
  let formEnabled = $state(true);
  const roleOptions = ["super_admin", "admin", "operator", "viewer"];
  function resetForm() {
    formEmail = "";
    formRole = "viewer";
    formEnabled = true;
  }
  async function loadConfig() {
    const c = getStoredCredentials();
    if (!c) return;
    const cl = createClient(c.url, c.token);
    try {
      const s = await cl.getConfigStoreSnapshot();
      const sec = s.sections["accounts"];
      if (
        sec?.data &&
        typeof sec.data === "object" &&
        "accounts" in (sec.data as Record<string, unknown>)
      )
        accounts = (sec.data as AccountsConfig).accounts;
    } catch {
    } finally {
      loading = false;
    }
  }
  async function saveAccounts() {
    const c = getStoredCredentials();
    if (!c) return;
    const cl = createClient(c.url, c.token);
    saving = true;
    error = "";
    success = "";
    try {
      await cl.putConfigStoreSection("accounts", { accounts });
      success = "Saved";
      editAccountEmail = null;
      showCreateForm = false;
    } catch (e) {
      error = e instanceof Error ? e.message : "Failed";
    } finally {
      saving = false;
    }
  }
  function startCreate() {
    resetForm();
    showCreateForm = true;
    editAccountEmail = null;
  }
  function startEdit(email: string) {
    const a = accounts.find((x) => x.email === email);
    if (!a) return;
    formEmail = a.email;
    formRole = a.role;
    formEnabled = a.enabled;
    editAccountEmail = email;
    showCreateForm = false;
  }
  function cancelEdit() {
    editAccountEmail = null;
    showCreateForm = false;
    resetForm();
  }
  function applyCreate() {
    if (!formEmail.trim()) {
      error = "Email required";
      return;
    }
    if (accounts.some((a) => a.email === formEmail.trim())) {
      error = "Exists";
      return;
    }
    error = "";
    accounts = [
      ...accounts,
      {
        email: formEmail.trim(),
        role: formRole,
        enabled: formEnabled,
        createdAt: Date.now()
      }
    ];
    showCreateForm = false;
    resetForm();
    saveAccounts();
  }
  function applyEdit() {
    if (!editAccountEmail || !formEmail.trim()) {
      error = "Email required";
      return;
    }
    error = "";
    accounts = accounts.map((a) =>
      a.email === editAccountEmail
        ? {
            ...a,
            email: formEmail.trim(),
            role: formRole,
            enabled: formEnabled
          }
        : a
    );
    editAccountEmail = null;
    resetForm();
    saveAccounts();
  }
  function toggleEnabled(email: string) {
    accounts = accounts.map((a) =>
      a.email === email ? { ...a, enabled: !a.enabled } : a
    );
    saveAccounts();
  }
  function deleteAccount(email: string) {
    if (!confirm(`Delete ${email}?`)) return;
    accounts = accounts.filter((a) => a.email !== email);
    saveAccounts();
  }
  function roleBadgeVariant(
    role: string
  ): "destructive" | "secondary" | "outline" | "default" {
    switch (role) {
      case "super_admin":
        return "destructive";
      case "admin":
        return "secondary";
      case "operator":
        return "outline";
      default:
        return "default";
    }
  }
  loadConfig();
</script>

<svelte:head><title>Accounts - Airlock</title></svelte:head>

<Breadcrumb.Root>
  <Breadcrumb.List>
    <Breadcrumb.Item
      ><Breadcrumb.Link href="/config">Config</Breadcrumb.Link></Breadcrumb.Item
    >
    <Breadcrumb.Separator />
    <Breadcrumb.Item
      ><Breadcrumb.Page>Accounts</Breadcrumb.Page></Breadcrumb.Item
    >
  </Breadcrumb.List>
</Breadcrumb.Root>

<div class="flex items-center justify-between mb-3 mt-1">
  <h1 class="text-xl font-semibold tracking-tight">Account Management</h1>
  {#if !loading}
    <Button size="sm" onclick={startCreate}
      ><Plus data-icon="inline-start" />Add Account</Button
    >
  {/if}
</div>

{#if error}
  <div
    class="rounded-lg border border-destructive/30 bg-destructive/5 p-2.5 mb-3 text-xs text-destructive"
  >
    {error}
  </div>
{/if}
{#if success}
  <div
    class="rounded-lg border border-success/30 bg-success/5 p-2.5 mb-3 text-xs text-success"
  >
    {success}
  </div>
{/if}

{#if loading}
  <Card.Root class="py-4 text-center">
    <Card.Content
      ><p class="text-sm text-muted-foreground">Loading...</p></Card.Content
    >
  </Card.Root>
{:else}
  {#if showCreateForm || editAccountEmail}
    <Card.Root class="mb-3">
      <Card.Header>
        <h3 class="text-sm font-semibold">
          {editAccountEmail ? "Edit Account" : "Add Account"}
        </h3>
      </Card.Header>
      <Card.Content class="grid gap-2.5">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-2.5">
          <div class="grid gap-1">
            <Label for="ae">Email</Label>
            <Input
              id="ae"
              type="email"
              placeholder="user@example.com"
              bind:value={formEmail}
              disabled={editAccountEmail !== null}
            />
          </div>
          <div class="grid gap-1">
            <Label for="ar">Role</Label>
            <select
              id="ar"
              bind:value={formRole}
              class="border-input bg-background flex h-8 w-full rounded-lg border px-2.5 py-1 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring/50"
            >
              {#each roleOptions as r}<option value={r}>{r}</option>{/each}
            </select>
          </div>
        </div>
        <div class="flex items-center gap-2">
          <Switch bind:checked={formEnabled} />
          <Label class="!gap-0 text-xs">Enabled</Label>
        </div>
      </Card.Content>
      <Card.Footer class="justify-end gap-1.5">
        <Button variant="outline" size="sm" onclick={cancelEdit}>Cancel</Button>
        <Button
          size="sm"
          onclick={editAccountEmail ? applyEdit : applyCreate}
          disabled={saving}
        >
          <Save data-icon="inline-start" />{saving ? "Saving..." : "Save"}
        </Button>
      </Card.Footer>
    </Card.Root>
  {/if}

  <!-- Desktop: Table -->
  <div class="hidden md:block">
    <Table.Root>
      <Table.Header>
        <Table.Row>
          <Table.Head>Email</Table.Head>
          <Table.Head>Role</Table.Head>
          <Table.Head>Status</Table.Head>
          <Table.Head class="text-right">Actions</Table.Head>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {#each accounts as account}
          <Table.Row>
            <Table.Cell class="font-mono text-xs">{account.email}</Table.Cell>
            <Table.Cell>
              <Badge variant={roleBadgeVariant(account.role)}
                >{account.role}</Badge
              >
            </Table.Cell>
            <Table.Cell>
              <button
                onclick={() => toggleEnabled(account.email)}
                class="flex items-center gap-1.5 cursor-pointer"
              >
                <span
                  class="size-2 rounded-full {account.enabled
                    ? 'bg-success'
                    : 'bg-muted-foreground'}"
                ></span>
                <span class="text-xs"
                  >{account.enabled ? "Active" : "Disabled"}</span
                >
              </button>
            </Table.Cell>
            <Table.Cell>
              <div class="flex justify-end gap-1">
                <Button
                  variant="ghost"
                  size="xs"
                  onclick={() => startEdit(account.email)}
                >
                  <Pencil data-icon="inline-start" />Edit
                </Button>
                <Button
                  variant="destructive"
                  size="xs"
                  onclick={() => deleteAccount(account.email)}
                >
                  <Trash2 data-icon="inline-start" />Delete
                </Button>
              </div>
            </Table.Cell>
          </Table.Row>
        {/each}
        {#if accounts.length === 0}
          <Table.Row>
            <Table.Cell
              colspan={4}
              class="py-4 text-center text-sm text-muted-foreground"
            >
              No accounts configured.
            </Table.Cell>
          </Table.Row>
        {/if}
      </Table.Body>
    </Table.Root>
  </div>

  <!-- Mobile: Card list -->
  <div class="md:hidden grid gap-2">
    {#each accounts as account}
      <Card.Root size="sm">
        <Card.Content>
          <div class="flex items-center justify-between mb-2">
            <span class="font-mono text-xs">{account.email}</span>
            <Badge variant={roleBadgeVariant(account.role)}
              >{account.role}</Badge
            >
          </div>
          <div class="flex items-center justify-between">
            <button
              onclick={() => toggleEnabled(account.email)}
              class="flex items-center gap-1.5 cursor-pointer"
            >
              <span
                class="size-2 rounded-full {account.enabled
                  ? 'bg-success'
                  : 'bg-muted-foreground'}"
              ></span>
              <span class="text-xs"
                >{account.enabled ? "Active" : "Disabled"}</span
              >
            </button>
            <div class="flex gap-1">
              <Button
                variant="ghost"
                size="xs"
                onclick={() => startEdit(account.email)}
              >
                <Pencil data-icon="inline-start" />Edit
              </Button>
              <Button
                variant="destructive"
                size="xs"
                onclick={() => deleteAccount(account.email)}
              >
                <Trash2 data-icon="inline-start" />Delete
              </Button>
            </div>
          </div>
        </Card.Content>
      </Card.Root>
    {/each}
    {#if accounts.length === 0}
      <Card.Root class="py-4 text-center">
        <Card.Content
          ><p class="text-sm text-muted-foreground">
            No accounts configured.
          </p></Card.Content
        >
      </Card.Root>
    {/if}
  </div>
{/if}

// apps/console/src/routes/config/accounts.tsx
import { createFileRoute } from "@tanstack/react-router";
import {
  Button,
  Card,
  Chip,
  EmptyState,
  Input,
  Modal,
  Select,
  Skeleton,
  Switch,
  Table,
  toast,
  useOverlayState,
  ListBox,
  ListBoxItem,
} from "@heroui/react";
import { FiPlus, FiUsers } from "react-icons/fi";
import { useState } from "react";
import {
  useConfigStoreSection,
  usePutConfigStoreSection,
} from "../../hooks/use-queries";

export const Route = createFileRoute("/config/accounts")({
  component: AccountsPage,
});

const ROLES = ["super_admin", "admin", "operator", "viewer"];

interface Account {
  email: string;
  role: string;
  enabled: boolean;
}

const ROLE_COLORS: Record<string, "accent" | "default" | "success" | "warning"> = {
  super_admin: "accent",
  admin: "default",
  operator: "success",
  viewer: "warning",
};

function AccountsPage() {
  const section = useConfigStoreSection("accounts");
  const putSection = usePutConfigStoreSection("accounts");
  const modalState = useOverlayState();
  const deleteModalState = useOverlayState();

  const accounts = (section.data?.data as Account[]) ?? [];

  const [editEmail, setEditEmail] = useState("");
  const [isEditing, setIsEditing] = useState(false);
  const [editRole, setEditRole] = useState<string | null>("viewer");
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null);

  function openEdit(account?: Account) {
    if (account) {
      setEditEmail(account.email);
      setIsEditing(true);
      setEditRole(account.role);
    } else {
      setEditEmail("");
      setIsEditing(false);
      setEditRole("viewer");
    }
    modalState.open();
  }

  function handleSave() {
    if (!editEmail.trim()) {
      toast.danger("Email is required.");
      return;
    }
    const existing = accounts.filter((a) => a.email !== editEmail);
    const existingAccount = accounts.find((a) => a.email === editEmail);
    const enabled = isEditing ? (existingAccount?.enabled ?? true) : true;
    const updated = [
      ...existing,
      { email: editEmail, role: editRole ?? "viewer", enabled },
    ];
    putSection.mutate(updated, {
      onSuccess: () => {
        toast.success(`Account "${editEmail}" ${isEditing ? "updated" : "created"} successfully.`);
        modalState.close();
      },
      onError: (err) => {
        toast.danger(`Failed to save account: ${err instanceof Error ? err.message : "Unknown error"}`);
      },
    });
  }

  function handleToggle(email: string, enabled: boolean) {
    const updated = accounts.map((a) =>
      a.email === email ? { ...a, enabled } : a
    );
    putSection.mutate(updated, {
      onSuccess: () => {
        toast.success(`Account "${email}" ${enabled ? "enabled" : "disabled"}.`);
      },
      onError: (err) => {
        toast.danger(`Failed to update account: ${err instanceof Error ? err.message : "Unknown error"}`);
      },
    });
  }

  function confirmDelete(email: string) {
    setDeleteTarget(email);
    deleteModalState.open();
  }

  function handleDelete() {
    if (!deleteTarget) return;
    const updated = accounts.filter((a) => a.email !== deleteTarget);
    putSection.mutate(updated, {
      onSuccess: () => {
        toast.success(`Account "${deleteTarget}" deleted.`);
        deleteModalState.close();
        setDeleteTarget(null);
      },
      onError: (err) => {
        toast.danger(`Failed to delete account: ${err instanceof Error ? err.message : "Unknown error"}`);
      },
    });
  }

  return (
    <div className="p-6 space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Accounts</h1>
          <p className="text-sm text-default-400">Manage admin access</p>
        </div>
        <Button variant="primary" onPress={() => openEdit()}>
          <FiPlus size={16} /> Add Account
        </Button>
      </div>

      {section.isLoading ? (
        <Card.Root>
          <Card.Content className="p-0">
            <div className="p-4 space-y-3">
              <div className="flex gap-4">
                <Skeleton animationType="pulse" className="h-4 w-40 rounded" />
                <Skeleton animationType="pulse" className="h-4 w-24 rounded" />
                <Skeleton animationType="pulse" className="h-4 w-20 rounded" />
                <Skeleton animationType="pulse" className="h-4 w-24 rounded" />
              </div>
              {Array.from({ length: 3 }).map((_, i) => (
                <div key={i} className="flex gap-4">
                  <Skeleton animationType="pulse" className="h-8 w-40 rounded" />
                  <Skeleton animationType="pulse" className="h-6 w-24 rounded-full" />
                  <Skeleton animationType="pulse" className="h-6 w-10 rounded" />
                  <Skeleton animationType="pulse" className="h-8 w-24 rounded" />
                </div>
              ))}
            </div>
          </Card.Content>
        </Card.Root>
      ) : accounts.length === 0 ? (
        <Card.Root className="border-dashed border-2 border-default-200">
          <Card.Content className="py-12">
            <EmptyState.Root>
              <div className="flex flex-col items-center gap-3 text-center">
                <div className="flex h-14 w-14 items-center justify-center rounded-full bg-default-100">
                  <FiUsers size={24} className="text-default-400" />
                </div>
                <div>
                  <p className="text-lg font-medium text-default-700">No accounts configured</p>
                  <p className="text-sm text-default-400 mt-1">Add an account to manage admin access</p>
                </div>
                <Button variant="primary" onPress={() => openEdit()} className="mt-2">
                  <FiPlus size={16} /> Add Account
                </Button>
              </div>
            </EmptyState.Root>
          </Card.Content>
        </Card.Root>
      ) : (
        <Card.Root>
          <Card.Content className="p-0">
            <Table.Root aria-label="Accounts">
              <Table.Header>
                <Table.Column isRowHeader>Email</Table.Column>
                <Table.Column>Role</Table.Column>
                <Table.Column>Status</Table.Column>
                <Table.Column>Actions</Table.Column>
              </Table.Header>
              <Table.Body>
                {accounts.map((account) => (
                  <Table.Row key={account.email} className="hover:bg-default-50">
                    <Table.Cell>
                      <span className="font-mono text-sm">{account.email}</span>
                    </Table.Cell>
                    <Table.Cell>
                      <Chip
                        size="sm"
                        variant="soft"
                        color={ROLE_COLORS[account.role] ?? "default"}
                      >
                        {account.role}
                      </Chip>
                    </Table.Cell>
                    <Table.Cell>
                      <div className="flex items-center gap-2">
                        <Switch.Root
                          size="sm"
                          isSelected={account.enabled}
                          onChange={(v) => handleToggle(account.email, v)}
                        >
                          <Switch.Control>
                            <Switch.Thumb />
                          </Switch.Control>
                        </Switch.Root>
                        <span className="text-xs text-default-400">
                          {account.enabled ? "Enabled" : "Disabled"}
                        </span>
                      </div>
                    </Table.Cell>
                    <Table.Cell>
                      <div className="flex gap-1">
                        <Button
                          size="sm"
                          variant="ghost"
                          onPress={() => openEdit(account)}
                        >
                          Edit
                        </Button>
                        <Button
                          size="sm"
                          variant="danger-soft"
                          onPress={() => confirmDelete(account.email)}
                        >
                          Delete
                        </Button>
                      </div>
                    </Table.Cell>
                  </Table.Row>
                ))}
              </Table.Body>
            </Table.Root>
          </Card.Content>
        </Card.Root>
      )}

      {/* Add/Edit Modal */}
      <Modal.Root state={modalState}>
        <Modal.Backdrop>
          <Modal.Container>
            <Modal.Dialog>
              <Modal.Header>
                {isEditing ? "Edit Account" : "Add Account"}
              </Modal.Header>
              <Modal.Body className="gap-4">
                <div className="flex flex-col gap-1.5">
                  <label className="text-sm font-medium">Email</label>
                  <Input
                    type="email"
                    placeholder="user@example.com"
                    value={editEmail}
                    onChange={(e) => setEditEmail(e.target.value)}
                  />
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-sm font-medium">Role</label>
                  <Select.Root
                    selectedKey={editRole}
                    onSelectionChange={(key) =>
                      setEditRole(key as string | null)
                    }
                  >
                    <Select.Trigger />
                    <Select.Value>
                      {({ isPlaceholder }) =>
                        isPlaceholder ? "Select role" : undefined
                      }
                    </Select.Value>
                    <Select.Indicator />
                    <Select.Popover>
                      <ListBox>
                        {ROLES.map((r) => (
                          <ListBoxItem key={r} textValue={r}>
                            <div className="flex items-center gap-2">
                              <Chip size="sm" variant="soft" color={ROLE_COLORS[r] ?? "default"}>
                                {r}
                              </Chip>
                            </div>
                          </ListBoxItem>
                        ))}
                      </ListBox>
                    </Select.Popover>
                  </Select.Root>
                </div>
              </Modal.Body>
              <Modal.Footer>
                <Button variant="ghost" onPress={modalState.close}>
                  Cancel
                </Button>
                <Button
                  variant="primary"
                  onPress={handleSave}
                  isPending={putSection.isPending}
                >
                  Save
                </Button>
              </Modal.Footer>
            </Modal.Dialog>
          </Modal.Container>
        </Modal.Backdrop>
      </Modal.Root>

      {/* Delete Confirmation Modal */}
      <Modal.Root state={deleteModalState}>
        <Modal.Backdrop>
          <Modal.Container>
            <Modal.Dialog>
              <Modal.Header>Delete Account</Modal.Header>
              <Modal.Body>
                <p className="text-sm text-default-500">
                  Are you sure you want to delete account{" "}
                  <span className="font-mono font-semibold text-foreground">{deleteTarget}</span>? This action cannot be undone.
                </p>
              </Modal.Body>
              <Modal.Footer>
                <Button variant="ghost" onPress={deleteModalState.close}>
                  Cancel
                </Button>
                <Button
                  variant="danger"
                  onPress={handleDelete}
                  isPending={putSection.isPending}
                >
                  Delete
                </Button>
              </Modal.Footer>
            </Modal.Dialog>
          </Modal.Container>
        </Modal.Backdrop>
      </Modal.Root>
    </div>
  );
}
