// apps/dashboard/src/routes/+page.svelte
<script lang="ts">
  import Nav from "$components/Nav.svelte";
  import type {
    GatewayStatusResponse,
    MetricsSnapshot,
    RoutingHealthResponse
  } from "$lib/api.js";

  let { data } = $props<{
    data: {
      status: GatewayStatusResponse | null;
      metrics: MetricsSnapshot | null;
      routingHealth: RoutingHealthResponse | null;
    };
  }>();
</script>

<Nav />

<main class="max-w-7xl mx-auto px-6 py-8">
  <h2 class="text-xl font-bold text-gray-100 mb-6">Dashboard</h2>

  {#if data.status}
    <!-- Status Cards -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
      <div class="bg-gray-900 border border-gray-800 rounded-lg p-4">
        <p class="text-sm text-gray-400">Mode</p>
        <p class="text-lg font-semibold text-white">{data.status.mode}</p>
      </div>
      <div class="bg-gray-900 border border-gray-800 rounded-lg p-4">
        <p class="text-sm text-gray-400">Routes</p>
        <p class="text-lg font-semibold text-white">{data.status.routes.length}</p>
      </div>
      <div class="bg-gray-900 border border-gray-800 rounded-lg p-4">
        <p class="text-sm text-gray-400">Keys</p>
        <p class="text-lg font-semibold text-white">
          {data.status.keys.total}
          <span class="text-sm text-gray-500"
            >({data.status.keys.registryOwned} registry)</span
          >
        </p>
      </div>
      <div class="bg-gray-900 border border-gray-800 rounded-lg p-4">
        <p class="text-sm text-gray-400">Circuit Breakers</p>
        <p class="text-lg font-semibold text-white">
          {data.status.circuitBreaker.openTargets}
          <span class="text-sm text-gray-500">open / {data.status.circuitBreaker.totalTargets} total</span>
        </p>
      </div>
    </div>

    <!-- Providers -->
    <div class="mb-8">
      <h3 class="text-lg font-semibold text-gray-200 mb-3">Providers</h3>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        {#each data.status.providers as provider}
          <div class="bg-gray-900 border border-gray-800 rounded-lg p-4 flex items-center justify-between">
            <div>
              <p class="font-medium text-white">{provider.id}</p>
              <p class="text-sm text-gray-400">{provider.routeCount} route{provider.routeCount !== 1 ? 's' : ''}</p>
            </div>
            <span
              class="px-2 py-1 rounded text-xs font-medium {provider.configured
                ? 'bg-green-900 text-green-300'
                : 'bg-gray-800 text-gray-500'}"
            >
              {provider.configured ? "Configured" : "Not configured"}
            </span>
          </div>
        {/each}
      </div>
    </div>

    <!-- Metrics -->
    {#if data.metrics}
      <div class="mb-8">
        <h3 class="text-lg font-semibold text-gray-200 mb-3">Request Metrics</h3>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div class="bg-gray-900 border border-gray-800 rounded-lg p-4">
            <p class="text-sm text-gray-400">Total Requests</p>
            <p class="text-2xl font-bold text-white">{data.metrics.requests.total}</p>
          </div>
          <div class="bg-gray-900 border border-gray-800 rounded-lg p-4">
            <p class="text-sm text-gray-400">Error Rate</p>
            <p class="text-2xl font-bold text-white">
              {data.metrics.requests.total > 0
                ? ((data.metrics.requests.errors / data.metrics.requests.total) * 100).toFixed(1)
                : 0}%
            </p>
          </div>
          <div class="bg-gray-900 border border-gray-800 rounded-lg p-4">
            <p class="text-sm text-gray-400">Avg Latency</p>
            <p class="text-2xl font-bold text-white">{data.metrics.requests.avgDurationMs.toFixed(0)}ms</p>
          </div>
        </div>
      </div>
    {/if}

    <!-- Routing Health -->
    {#if data.routingHealth?.routes}
      <div>
        <h3 class="text-lg font-semibold text-gray-200 mb-3">Route Health</h3>
        <div class="bg-gray-900 border border-gray-800 rounded-lg overflow-hidden">
          <table class="w-full text-sm">
            <thead>
              <tr class="border-b border-gray-800 text-gray-400 text-left">
                <th class="px-4 py-3">Route</th>
                <th class="px-4 py-3">Status</th>
                <th class="px-4 py-3">Healthy / Total</th>
                <th class="px-4 py-3">Strategy</th>
              </tr>
            </thead>
            <tbody>
              {#each Object.entries(data.routingHealth.routes) as [name, route]}
                <tr class="border-b border-gray-800 last:border-0">
                  <td class="px-4 py-3 text-white font-medium">{name}</td>
                  <td class="px-4 py-3">
                    <span
                      class="px-2 py-1 rounded text-xs font-medium {route.healthStatus ===
                      'healthy'
                        ? 'bg-green-900 text-green-300'
                        : route.healthStatus === 'degraded'
                          ? 'bg-yellow-900 text-yellow-300'
                          : 'bg-red-900 text-red-300'}"
                    >
                      {route.healthStatus}
                    </span>
                  </td>
                  <td class="px-4 py-3 text-gray-300"
                    >{route.healthyTargetCount} / {route.totalTargetCount}</td
                  >
                  <td class="px-4 py-3 text-gray-400">{route.strategy ?? "default"}</td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      </div>
    {/if}
  {:else}
    <div class="bg-gray-900 border border-gray-800 rounded-lg p-8 text-center">
      <p class="text-gray-400">Failed to load gateway status. Check your connection.</p>
    </div>
  {/if}
</main>

// apps/console/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import {
  Card,
  Chip,
  ProgressBar,
  Spinner,
  Table,
} from "@heroui/react";
import { useStatus, useMetrics, useRoutingHealth } from "../hooks/use-queries";

export const Route = createFileRoute("/")({
  component: DashboardPage,
});

function DashboardPage() {
  const status = useStatus();
  const metrics = useMetrics();
  const health = useRoutingHealth();

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold">Dashboard</h1>

      {status.isLoading ? (
        <div className="flex justify-center py-20">
          <Spinner size="lg" />
        </div>
      ) : status.data ? (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <StatusCard
              title="Providers"
              value={String(status.data.providers.length)}
              subtitle={`${status.data.providers.filter((p) => p.configured).length} configured`}
              color="accent"
            />
            <StatusCard
              title="Routes"
              value={String(status.data.routes.length)}
              subtitle={`${status.data.providers.reduce((a, p) => a + p.routeCount, 0)} targets`}
              color="default"
            />
            <StatusCard
              title="Keys"
              value={String(status.data.keys.total)}
              subtitle={`${status.data.keys.registryOwned} registry`}
              color="success"
            />
            <StatusCard
              title="Circuit Breakers"
              value={String(status.data.circuitBreaker.openTargets.length)}
              subtitle={`${status.data.circuitBreaker.halfOpenTargets.length} half-open`}
              color={
                status.data.circuitBreaker.openTargets.length > 0
                  ? "danger"
                  : "success"
              }
            />
          </div>

          {metrics.data && (
            <Card.Root>
              <Card.Header>
                <h2 className="text-lg font-semibold">
                  Metrics{" "}
                  <span className="text-sm text-default-400 font-normal">
                    (live, 10s refresh)
                  </span>
                </h2>
              </Card.Header>
              <Card.Content>
                <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
                  <MetricItem
                    label="Requests"
                    value={metrics.data.requests}
                  />
                  <MetricItem
                    label="Errors"
                    value={metrics.data.errors}
                    color={metrics.data.errorRate > 0.05 ? "danger" : "default"}
                  />
                  <MetricItem
                    label="Error Rate"
                    value={`${(metrics.data.errorRate * 100).toFixed(1)}%`}
                    color={metrics.data.errorRate > 0.05 ? "danger" : "default"}
                  />
                  <MetricItem
                    label="Avg Latency"
                    value={`${metrics.data.avgDurationMs.toFixed(0)}ms`}
                  />
                  <MetricItem
                    label="Streams"
                    value={`${(metrics.data.streamRatio * 100).toFixed(0)}%`}
                  />
                </div>
              </Card.Content>
            </Card.Root>
          )}

          {health.data && (
            <Card.Root>
              <Card.Header>
                <h2 className="text-lg font-semibold">Route Health</h2>
              </Card.Header>
              <Card.Content>
                <Table.Root aria-label="Route health">
                  <Table.Header>
                    <Table.Column isRowHeader>Route</Table.Column>
                    <Table.Column>Status</Table.Column>
                    <Table.Column>Strategy</Table.Column>
                    <Table.Column>Targets</Table.Column>
                    <Table.Column>Health</Table.Column>
                  </Table.Header>
                  <Table.Body>
                    {Object.entries(health.data.routes).map(
                      ([route, info]) => (
                        <Table.Row key={route}>
                          <Table.Cell className="font-mono text-sm">
                            {route}
                          </Table.Cell>
                          <Table.Cell>
                            <HealthChip status={info.healthStatus} />
                          </Table.Cell>
                          <Table.Cell className="text-sm">
                            {info.strategy}
                          </Table.Cell>
                          <Table.Cell className="text-sm">
                            {info.healthyTargetCount}/{info.totalTargetCount}
                          </Table.Cell>
                          <Table.Cell>
                            <ProgressBar.Root
                              value={
                                (info.healthyTargetCount /
                                  info.totalTargetCount) *
                                100
                              }
                              color={
                                info.healthStatus === "healthy"
                                  ? "success"
                                  : info.healthStatus === "degraded"
                                    ? "warning"
                                    : "danger"
                              }
                              className="w-24"
                            />
                          </Table.Cell>
                        </Table.Row>
                      )
                    )}
                  </Table.Body>
                </Table.Root>
              </Card.Content>
            </Card.Root>
          )}
        </>
      ) : (
        <p className="text-danger">{String(status.error)}</p>
      )}
    </div>
  );
}

function StatusCard({
  title,
  value,
  subtitle,
  color,
}: {
  title: string;
  value: string;
  subtitle: string;
  color: "accent" | "default" | "success" | "danger" | "warning";
}) {
  return (
    <Card.Root>
      <Card.Content className="gap-1">
        <p className="text-sm text-default-500">{title}</p>
        <p className="text-2xl font-bold">{value}</p>
        <Chip size="sm" variant="soft" color={color}>
          {subtitle}
        </Chip>
      </Card.Content>
    </Card.Root>
  );
}

function MetricItem({
  label,
  value,
  color = "default",
}: {
  label: string;
  value: string | number;
  color?: "default" | "danger";
}) {
  return (
    <div className="text-center">
      <p className="text-sm text-default-400">{label}</p>
      <p
        className={`text-xl font-semibold ${
          color === "danger" ? "text-danger" : ""
        }`}
      >
        {value}
      </p>
    </div>
  );
}

function HealthChip({
  status,
}: {
  status: "healthy" | "degraded" | "down";
}) {
  const color = { healthy: "success", degraded: "warning", down: "danger" }[
    status
  ] as "success" | "warning" | "danger";
  return (
    <Chip size="sm" variant="soft" color={color}>
      {status}
    </Chip>
  );
}
