// apps/dashboard/src/routes/login/+page.svelte
<script lang="ts">
  import { verifyCredentials, storeCredentials } from "$lib/auth.js";

  let url = $state("");
  let token = $state("");
  let error = $state("");
  let loading = $state(false);

  async function handleSubmit(e: Event) {
    e.preventDefault();
    error = "";
    loading = true;
    try {
      const valid = await verifyCredentials(url, token);
      if (valid) {
        storeCredentials(url, token);
        window.location.href = "/";
      } else {
        error = "Invalid credentials";
      }
    } catch (err) {
      error = err instanceof Error ? err.message : "Connection failed";
    } finally {
      loading = false;
    }
  }
</script>

<div class="min-h-screen bg-gray-950 flex items-center justify-center">
  <div class="bg-gray-900 rounded-lg p-8 w-full max-w-md border border-gray-800">
    <h1 class="text-2xl font-bold text-white mb-6">Airlock Dashboard</h1>

    <form onsubmit={handleSubmit} class="space-y-4">
      <div>
        <label for="url" class="block text-sm font-medium text-gray-300 mb-1"
          >Gateway URL</label
        >
        <input
          id="url"
          type="url"
          bind:value={url}
          placeholder="https://your-gateway.workers.dev"
          required
          class="w-full bg-gray-800 border border-gray-700 rounded-md px-3 py-2 text-white placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label for="token" class="block text-sm font-medium text-gray-300 mb-1"
          >Admin Token</label
        >
        <input
          id="token"
          type="password"
          bind:value={token}
          placeholder="Bearer token"
          required
          class="w-full bg-gray-800 border border-gray-700 rounded-md px-3 py-2 text-white placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      {#if error}
        <p class="text-red-400 text-sm">{error}</p>
      {/if}

      <button
        type="submit"
        disabled={loading}
        class="w-full bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white font-medium py-2 px-4 rounded-md transition-colors"
      >
        {loading ? "Connecting..." : "Connect"}
      </button>
    </form>
  </div>
</div>

// apps/console/src/routes/login.tsx
import { createFileRoute, redirect, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Card, Input, Button } from "@heroui/react";
import { FiLock } from "react-icons/fi";
import { verifyCredentials, storeCredentials, getStoredCredentials } from "../lib/auth";

export const Route = createFileRoute("/login")({
  beforeLoad: () => {
    if (getStoredCredentials()) throw redirect({ to: "/" });
  },
  component: LoginPage,
});

function LoginPage() {
  const navigate = useNavigate();
  const [url, setUrl] = useState("");
  const [token, setToken] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError("");
    try {
      const valid = await verifyCredentials(url, token);
      if (valid) {
        storeCredentials(url, token);
        await navigate({ to: "/" });
      } else {
        setError("Invalid credentials");
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Connection failed");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-content1">
      <Card.Root className="w-full max-w-md">
        <Card.Header className="flex gap-3">
          <div className="flex items-center justify-center w-10 h-10 rounded-lg bg-primary text-primary-foreground">
            <FiLock size={20} />
          </div>
          <div>
            <h1 className="text-xl font-bold">Airlock Console</h1>
            <p className="text-sm text-default-500">AI Gateway</p>
          </div>
        </Card.Header>
        <Card.Content>
          <form onSubmit={handleSubmit} className="flex flex-col gap-4">
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium">Gateway URL</label>
              <Input
                placeholder="https://your-gateway.workers.dev"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                required
              />
            </div>
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium">Admin Token</label>
              <Input
                type="password"
                placeholder="Your admin token"
                value={token}
                onChange={(e) => setToken(e.target.value)}
                required
              />
            </div>
            {error && <p className="text-sm text-danger">{error}</p>}
            <Button
              type="submit"
              variant="primary"
              isDisabled={loading}
              fullWidth
            >
              {loading ? "Connecting..." : "Connect"}
            </Button>
          </form>
        </Card.Content>
      </Card.Root>
    </div>
  );
}
