// apps/console/src/routes/config/routes.tsx
import { createFileRoute } from "@tanstack/react-router";
import {
  Button,
  Card,
  Chip,
  EmptyState,
  Input,
  Modal,
  Select,
  Skeleton,
  Table,
  toast,
  useOverlayState,
  ListBox,
  ListBoxItem,
} from "@heroui/react";
import { FiPlus, FiGitBranch } from "react-icons/fi";
import { useState } from "react";
import {
  useConfigStoreSection,
  usePutConfigStoreSection,
} from "../../hooks/use-queries";

export const Route = createFileRoute("/config/routes")({
  component: ConfigRoutesPage,
});

const STRATEGIES = [
  "weighted",
  "lowest_cost",
  "health_priority",
  "priority",
  "health_score",
];

interface RouteConfig {
  externalModel: string;
  target: { provider: string; providerModel: string };
  fallbacks?: Array<{ provider: string; providerModel: string }>;
  strategy?: string;
}

function ConfigRoutesPage() {
  const section = useConfigStoreSection("routes");
  const putSection = usePutConfigStoreSection("routes");
  const modalState = useOverlayState();
  const deleteModalState = useOverlayState();

  const routes = (section.data?.data as RouteConfig[]) ?? [];

  const [editModel, setEditModel] = useState("");
  const [isEditing, setIsEditing] = useState(false);
  const [editProvider, setEditProvider] = useState("");
  const [editProviderModel, setEditProviderModel] = useState("");
  const [editStrategy, setEditStrategy] = useState<string | null>("weighted");
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null);

  function openEdit(route?: RouteConfig) {
    if (route) {
      setEditModel(route.externalModel);
      setIsEditing(true);
      setEditProvider(route.target.provider);
      setEditProviderModel(route.target.providerModel);
      setEditStrategy(route.strategy ?? "weighted");
    } else {
      setEditModel("");
      setIsEditing(false);
      setEditProvider("");
      setEditProviderModel("");
      setEditStrategy("weighted");
    }
    modalState.open();
  }

  function handleSave() {
    if (!editModel.trim() || !editProvider.trim() || !editProviderModel.trim()) {
      toast.danger("All fields are required.");
      return;
    }
    const existing = routes.filter((r) => r.externalModel !== editModel);
    const updated = [
      ...existing,
      {
        externalModel: editModel,
        target: { provider: editProvider, providerModel: editProviderModel },
        strategy: editStrategy ?? "weighted",
      },
    ];
    putSection.mutate(updated, {
      onSuccess: () => {
        toast.success(`Route "${editModel}" ${isEditing ? "updated" : "created"} successfully.`);
        modalState.close();
      },
      onError: (err) => {
        toast.danger(`Failed to save route: ${err instanceof Error ? err.message : "Unknown error"}`);
      },
    });
  }

  function confirmDelete(model: string) {
    setDeleteTarget(model);
    deleteModalState.open();
  }

  function handleDelete() {
    if (!deleteTarget) return;
    const updated = routes.filter((r) => r.externalModel !== deleteTarget);
    putSection.mutate(updated, {
      onSuccess: () => {
        toast.success(`Route "${deleteTarget}" deleted.`);
        deleteModalState.close();
        setDeleteTarget(null);
      },
      onError: (err) => {
        toast.danger(`Failed to delete route: ${err instanceof Error ? err.message : "Unknown error"}`);
      },
    });
  }

  return (
    <div className="p-6 space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Route Configuration</h1>
          <p className="text-sm text-default-400">Map external models to providers</p>
        </div>
        <Button variant="primary" onPress={() => openEdit()}>
          <FiPlus size={16} /> Add Route
        </Button>
      </div>

      {section.isLoading ? (
        <Card.Root>
          <Card.Content className="p-0">
            <div className="p-4 space-y-3">
              <div className="flex gap-4">
                <Skeleton animationType="pulse" className="h-4 w-32 rounded" />
                <Skeleton animationType="pulse" className="h-4 w-28 rounded" />
                <Skeleton animationType="pulse" className="h-4 w-20 rounded" />
                <Skeleton animationType="pulse" className="h-4 w-24 rounded" />
                <Skeleton animationType="pulse" className="h-4 w-20 rounded" />
              </div>
              {Array.from({ length: 4 }).map((_, i) => (
                <div key={i} className="flex gap-4">
                  <Skeleton animationType="pulse" className="h-8 w-32 rounded" />
                  <Skeleton animationType="pulse" className="h-8 w-28 rounded" />
                  <Skeleton animationType="pulse" className="h-8 w-20 rounded" />
                  <Skeleton animationType="pulse" className="h-6 w-24 rounded-full" />
                  <Skeleton animationType="pulse" className="h-8 w-20 rounded" />
                </div>
              ))}
            </div>
          </Card.Content>
        </Card.Root>
      ) : routes.length === 0 ? (
        <Card.Root className="border-dashed border-2 border-default-200">
          <Card.Content className="py-12">
            <EmptyState.Root>
              <div className="flex flex-col items-center gap-3 text-center">
                <div className="flex h-14 w-14 items-center justify-center rounded-full bg-default-100">
                  <FiGitBranch size={24} className="text-default-400" />
                </div>
                <div>
                  <p className="text-lg font-medium text-default-700">No routes configured</p>
                  <p className="text-sm text-default-400 mt-1">Add a route to map models to providers</p>
                </div>
                <Button variant="primary" onPress={() => openEdit()} className="mt-2">
                  <FiPlus size={16} /> Add Route
                </Button>
              </div>
            </EmptyState.Root>
          </Card.Content>
        </Card.Root>
      ) : (
        <Card.Root>
          <Card.Content className="p-0">
            <Table.Root aria-label="Routes configuration">
              <Table.Header>
                <Table.Column isRowHeader>External Model</Table.Column>
                <Table.Column>Target</Table.Column>
                <Table.Column>Fallbacks</Table.Column>
                <Table.Column>Strategy</Table.Column>
                <Table.Column>Actions</Table.Column>
              </Table.Header>
              <Table.Body>
                {routes.map((route) => (
                  <Table.Row key={route.externalModel} className="hover:bg-default-50">
                    <Table.Cell>
                      <span className="font-mono text-sm">{route.externalModel}</span>
                    </Table.Cell>
                    <Table.Cell>
                      <span className="text-sm">
                        {route.target.provider}/{route.target.providerModel}
                      </span>
                    </Table.Cell>
                    <Table.Cell>
                      <div className="flex gap-1 flex-wrap">
                        {route.fallbacks?.length ? (
                          route.fallbacks.map((fb, i) => (
                            <Chip key={i} size="sm" variant="soft">
                              {fb.provider}/{fb.providerModel}
                            </Chip>
                          ))
                        ) : (
                          <span className="text-default-400">{"—"}</span>
                        )}
                      </div>
                    </Table.Cell>
                    <Table.Cell>
                      <Chip size="sm" variant="soft" color="accent">
                        {route.strategy ?? "weighted"}
                      </Chip>
                    </Table.Cell>
                    <Table.Cell>
                      <div className="flex gap-1">
                        <Button
                          size="sm"
                          variant="ghost"
                          onPress={() => openEdit(route)}
                        >
                          Edit
                        </Button>
                        <Button
                          size="sm"
                          variant="danger-soft"
                          onPress={() => confirmDelete(route.externalModel)}
                        >
                          Delete
                        </Button>
                      </div>
                    </Table.Cell>
                  </Table.Row>
                ))}
              </Table.Body>
            </Table.Root>
          </Card.Content>
        </Card.Root>
      )}

      {/* Add/Edit Modal */}
      <Modal.Root state={modalState}>
        <Modal.Backdrop>
          <Modal.Container>
            <Modal.Dialog>
              <Modal.Header>
                {isEditing ? "Edit Route" : "Add Route"}
              </Modal.Header>
              <Modal.Body className="gap-4">
                <div className="flex flex-col gap-1.5">
                  <label className="text-sm font-medium">External Model</label>
                  <Input
                    placeholder="e.g. gpt-4o"
                    value={editModel}
                    onChange={(e) => setEditModel(e.target.value)}
                  />
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-sm font-medium">Target Provider</label>
                  <Input
                    placeholder="e.g. openai-primary"
                    value={editProvider}
                    onChange={(e) => setEditProvider(e.target.value)}
                  />
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-sm font-medium">Target Model</label>
                  <Input
                    placeholder="e.g. gpt-4o"
                    value={editProviderModel}
                    onChange={(e) => setEditProviderModel(e.target.value)}
                  />
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-sm font-medium">Strategy</label>
                  <Select.Root
                    selectedKey={editStrategy}
                    onSelectionChange={(key) =>
                      setEditStrategy(key as string | null)
                    }
                  >
                    <Select.Trigger />
                    <Select.Value>
                      {({ isPlaceholder }) =>
                        isPlaceholder ? "Select strategy" : undefined
                      }
                    </Select.Value>
                    <Select.Indicator />
                    <Select.Popover>
                      <ListBox>
                        {STRATEGIES.map((s) => (
                          <ListBoxItem key={s} textValue={s}>
                            {s}
                          </ListBoxItem>
                        ))}
                      </ListBox>
                    </Select.Popover>
                  </Select.Root>
                </div>
              </Modal.Body>
              <Modal.Footer>
                <Button variant="ghost" onPress={modalState.close}>
                  Cancel
                </Button>
                <Button
                  variant="primary"
                  onPress={handleSave}
                  isPending={putSection.isPending}
                >
                  Save
                </Button>
              </Modal.Footer>
            </Modal.Dialog>
          </Modal.Container>
        </Modal.Backdrop>
      </Modal.Root>

      {/* Delete Confirmation Modal */}
      <Modal.Root state={deleteModalState}>
        <Modal.Backdrop>
          <Modal.Container>
            <Modal.Dialog>
              <Modal.Header>Delete Route</Modal.Header>
              <Modal.Body>
                <p className="text-sm text-default-500">
                  Are you sure you want to delete route{" "}
                  <span className="font-mono font-semibold text-foreground">{deleteTarget}</span>? This action cannot be undone.
                </p>
              </Modal.Body>
              <Modal.Footer>
                <Button variant="ghost" onPress={deleteModalState.close}>
                  Cancel
                </Button>
                <Button
                  variant="danger"
                  onPress={handleDelete}
                  isPending={putSection.isPending}
                >
                  Delete
                </Button>
              </Modal.Footer>
            </Modal.Dialog>
          </Modal.Container>
        </Modal.Backdrop>
      </Modal.Root>
    </div>
  );
}

// apps/dashboard/src/routes/config/routes/+page.svelte
<script lang="ts">
  import { createClient, getStoredCredentials } from "$lib/auth.js";
  import * as Breadcrumb from "$lib/components/ui/breadcrumb";
  import * as Card from "$lib/components/ui/card";
  import { Button } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";
  import { Label } from "$lib/components/ui/label";
  import { Badge } from "$lib/components/ui/badge";
  import Plus from "@lucide/svelte/icons/plus";
  import ArrowRight from "@lucide/svelte/icons/arrow-right";
  import Save from "@lucide/svelte/icons/save";
  import X from "@lucide/svelte/icons/x";
  import Pencil from "@lucide/svelte/icons/pencil";
  import Trash2 from "@lucide/svelte/icons/trash-2";

  type ProviderTarget = { provider: string; providerModel: string };
  type RouteConfig = {
    externalModel: string;
    target: ProviderTarget;
    fallbacks?: ProviderTarget[];
    strategy?: string;
    requiredKeyTier?: string;
    requiredKeyTags?: string[];
  };
  type RoutesConfig = RouteConfig[];
  type ProvidersConfig = Array<{ id: string; type: string; models?: string[] }>;

  let loading = $state(true);
  let saving = $state(false);
  let error = $state("");
  let success = $state("");
  let editRouteIndex = $state<number | null>(null);
  let showCreateForm = $state(false);
  let routes = $state<RoutesConfig>([]);
  let providerKeys = $state<string[]>([]);
  let providerModelsMap = $state<Record<string, string[]>>({});
  const strategyOptions = [
    "weighted",
    "lowest_cost",
    "health_priority",
    "priority",
    "health_score"
  ];
  let formExternalModel = $state("");
  let formTargetProvider = $state("");
  let formTargetModel = $state("");
  let formFallbacks = $state<ProviderTarget[]>([]);
  let formStrategy = $state("");
  let formRequiredKeyTier = $state("");
  let formRequiredKeyTags = $state("");

  const currentProviderModels = $derived(
    providerModelsMap[formTargetProvider] ?? []
  );

  function resetForm() {
    formExternalModel = "";
    formTargetProvider = providerKeys[0] ?? "";
    formTargetModel = "";
    formFallbacks = [];
    formStrategy = "";
    formRequiredKeyTier = "";
    formRequiredKeyTags = "";
  }
  function loadFormFromRoute(r: RouteConfig) {
    formExternalModel = r.externalModel;
    formTargetProvider = r.target.provider;
    formTargetModel = r.target.providerModel;
    formFallbacks = r.fallbacks ? r.fallbacks.map((f) => ({ ...f })) : [];
    formStrategy = r.strategy ?? "";
    formRequiredKeyTier = r.requiredKeyTier ?? "";
    formRequiredKeyTags = r.requiredKeyTags?.join(", ") ?? "";
  }
  async function loadConfig() {
    const c = getStoredCredentials();
    if (!c) return;
    const cl = createClient(c.url, c.token);
    try {
      const s = await cl.getConfigStoreSnapshot();
      const sec = s.sections["routes"];
      if (sec?.data && Array.isArray(sec.data))
        routes = sec.data as RoutesConfig;
      const ps = s.sections["providers"];
      if (ps?.data && Array.isArray(ps.data)) {
        const provs = ps.data as ProvidersConfig;
        providerKeys = provs.map((p) => p.id);
        providerModelsMap = {};
        for (const p of provs) {
          if (p.models?.length) providerModelsMap[p.id] = p.models;
        }
        if (!formTargetProvider && providerKeys[0])
          formTargetProvider = providerKeys[0];
      }
    } catch {
    } finally {
      loading = false;
    }
  }
  async function saveRoutes() {
    const c = getStoredCredentials();
    if (!c) return;
    const cl = createClient(c.url, c.token);
    saving = true;
    error = "";
    success = "";
    try {
      await cl.putConfigStoreSection("routes", routes);
      success = "Saved";
      editRouteIndex = null;
      showCreateForm = false;
    } catch (e) {
      error = e instanceof Error ? e.message : "Failed";
    } finally {
      saving = false;
    }
  }
  function startCreate() {
    resetForm();
    showCreateForm = true;
    editRouteIndex = null;
  }
  function startEdit(i: number) {
    loadFormFromRoute(routes[i]);
    editRouteIndex = i;
    showCreateForm = false;
  }
  function cancelEdit() {
    editRouteIndex = null;
    showCreateForm = false;
    resetForm();
  }
  function buildRoute(): RouteConfig {
    return {
      externalModel: formExternalModel.trim(),
      target: {
        provider: formTargetProvider,
        providerModel: formTargetModel.trim()
      },
      ...(formFallbacks.length > 0 ? { fallbacks: formFallbacks } : {}),
      ...(formStrategy ? { strategy: formStrategy } : {}),
      ...(formRequiredKeyTier.trim()
        ? { requiredKeyTier: formRequiredKeyTier.trim() }
        : {}),
      ...(formRequiredKeyTags.trim()
        ? {
            requiredKeyTags: formRequiredKeyTags
              .split(",")
              .map((t) => t.trim())
              .filter((t) => t)
          }
        : {})
    };
  }
  function applyCreate() {
    if (
      !formExternalModel.trim() ||
      !formTargetProvider.trim() ||
      !formTargetModel.trim()
    ) {
      error = "All fields required";
      return;
    }
    error = "";
    routes = [...routes, buildRoute()];
    showCreateForm = false;
    resetForm();
    saveRoutes();
  }
  function applyEdit() {
    if (editRouteIndex === null) return;
    if (
      !formExternalModel.trim() ||
      !formTargetProvider.trim() ||
      !formTargetModel.trim()
    ) {
      error = "All fields required";
      return;
    }
    error = "";
    routes = routes.map((r, i) => (i === editRouteIndex ? buildRoute() : r));
    editRouteIndex = null;
    resetForm();
    saveRoutes();
  }
  function deleteRoute(i: number) {
    if (!confirm("Delete?")) return;
    routes = routes.filter((_, j) => j !== i);
    saveRoutes();
  }
  function addFallback() {
    formFallbacks = [
      ...formFallbacks,
      { provider: providerKeys[0] ?? "", providerModel: "" }
    ];
  }
  function removeFallback(i: number) {
    formFallbacks = formFallbacks.filter((_, j) => j !== i);
  }
  function updateFallback(
    i: number,
    f: "provider" | "providerModel",
    v: string
  ) {
    formFallbacks = formFallbacks.map((fb, j) =>
      j === i ? { ...fb, [f]: v } : fb
    );
  }
  loadConfig();
</script>

<svelte:head><title>Routes - Airlock</title></svelte:head>

<Breadcrumb.Root>
  <Breadcrumb.List>
    <Breadcrumb.Item
      ><Breadcrumb.Link href="/config">Config</Breadcrumb.Link></Breadcrumb.Item
    >
    <Breadcrumb.Separator />
    <Breadcrumb.Item><Breadcrumb.Page>Routes</Breadcrumb.Page></Breadcrumb.Item>
  </Breadcrumb.List>
</Breadcrumb.Root>

<div class="flex items-center justify-between mb-3 mt-1">
  <h1 class="text-xl font-semibold tracking-tight">Route Configuration</h1>
  {#if !loading && providerKeys.length > 0}
    <Button size="sm" onclick={startCreate}
      ><Plus data-icon="inline-start" />Add Route</Button
    >
  {/if}
</div>

{#if error}
  <div
    class="rounded-lg border border-destructive/30 bg-destructive/5 p-2.5 mb-3 text-xs text-destructive"
  >
    {error}
  </div>
{/if}
{#if success}
  <div
    class="rounded-lg border border-success/30 bg-success/5 p-2.5 mb-3 text-xs text-success"
  >
    {success}
  </div>
{/if}

{#if loading}
  <Card.Root class="py-4 text-center">
    <Card.Content
      ><p class="text-sm text-muted-foreground">Loading...</p></Card.Content
    >
  </Card.Root>
{:else if providerKeys.length === 0}
  <Card.Root>
    <Card.Content>
      <p class="text-sm">Configure a provider first.</p>
      <Button variant="outline" size="sm" href="/config/providers" class="mt-2"
        >Add Provider</Button
      >
    </Card.Content>
  </Card.Root>
{:else}
  {#if showCreateForm}
    {@render routeForm("Create Route", applyCreate)}
  {/if}

  <div class="grid gap-1.5">
    {#each routes as route, index}
      {#if editRouteIndex === index}
        {@render routeForm("Edit Route", applyEdit)}
      {:else}
        <Card.Root size="sm">
          <Card.Content
            class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-1.5"
          >
            <div class="flex items-center gap-2 flex-wrap">
              <span class="text-sm font-medium font-mono"
                >{route.externalModel}</span
              >
              <ArrowRight class="size-3 text-muted-foreground" />
              <span class="text-xs">{route.target.provider}</span>
              <span class="font-mono text-[11px] text-muted-foreground"
                >{route.target.providerModel}</span
              >
              {#if route.fallbacks && route.fallbacks.length > 0}
                <Badge variant="outline">+{route.fallbacks.length} fb</Badge>
              {/if}
              {#if route.strategy}
                <Badge variant="secondary">{route.strategy}</Badge>
              {/if}
            </div>
            <div class="flex items-center gap-1 shrink-0">
              <Button
                variant="ghost"
                size="xs"
                onclick={() => startEdit(index)}
              >
                <Pencil data-icon="inline-start" />Edit
              </Button>
              <Button
                variant="destructive"
                size="xs"
                onclick={() => deleteRoute(index)}
              >
                <Trash2 data-icon="inline-start" />Delete
              </Button>
            </div>
          </Card.Content>
        </Card.Root>
      {/if}
    {/each}
    {#if routes.length === 0 && !showCreateForm}
      <Card.Root class="py-4 text-center">
        <Card.Content
          ><p class="text-sm text-muted-foreground">
            No routes configured.
          </p></Card.Content
        >
      </Card.Root>
    {/if}
  </div>
{/if}

{#snippet routeForm(title: string, onSave: () => void)}
  <Card.Root class="mb-3">
    <Card.Header>
      <h3 class="text-sm font-semibold">{title}</h3>
    </Card.Header>
    <Card.Content class="grid gap-3">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-2.5">
        <div class="grid gap-1">
          <Label for="re">External Model</Label>
          <Input
            id="re"
            type="text"
            placeholder="gpt-4.1-mini"
            bind:value={formExternalModel}
            class="font-mono"
          />
        </div>
        <div class="grid gap-1">
          <Label for="rs">Strategy</Label>
          <select
            id="rs"
            bind:value={formStrategy}
            class="border-input bg-background flex h-8 w-full rounded-lg border px-2.5 py-1 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring/50"
          >
            <option value="">Default</option>{#each strategyOptions as s}<option
                value={s}>{s}</option
              >{/each}
          </select>
        </div>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-2.5">
        <div class="grid gap-1">
          <Label for="rtp">Target Provider</Label>
          <select
            id="rtp"
            bind:value={formTargetProvider}
            class="border-input bg-background flex h-8 w-full rounded-lg border px-2.5 py-1 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring/50"
          >
            {#each providerKeys as p}<option value={p}>{p}</option>{/each}
          </select>
        </div>
        <div class="grid gap-1">
          <Label for="rtm">Target Model</Label>
          <input
            id="rtm"
            type="text"
            placeholder="gpt-4.1-mini"
            list="target-model-suggestions"
            bind:value={formTargetModel}
            class="border-input bg-background flex h-8 w-full rounded-lg border px-2.5 py-1 text-sm font-mono outline-none focus-visible:ring-2 focus-visible:ring-ring/50 placeholder:text-muted-foreground"
          />
          <datalist id="target-model-suggestions">
            {#each currentProviderModels as m}
              <option value={m}></option>
            {/each}
          </datalist>
        </div>
      </div>
      <div>
        <div class="flex items-center justify-between mb-1.5">
          <Label class="text-xs">Fallbacks</Label>
          <Button variant="ghost" size="xs" onclick={addFallback}
            ><Plus data-icon="inline-start" />Add</Button
          >
        </div>
        {#each formFallbacks as fb, i}
          <div class="flex items-center gap-1.5 mb-1.5">
            <select
              value={fb.provider}
              onchange={(e) =>
                updateFallback(
                  i,
                  "provider",
                  (e.target as HTMLSelectElement).value
                )}
              class="border-input bg-background flex h-7 rounded-lg border px-2 py-1 text-xs outline-none focus-visible:ring-2 focus-visible:ring-ring/50"
            >
              {#each providerKeys as p}<option value={p}>{p}</option>{/each}
            </select>
            <input
              type="text"
              placeholder="model"
              list="fb-model-suggestions-{i}"
              value={fb.providerModel}
              oninput={(e) =>
                updateFallback(
                  i,
                  "providerModel",
                  (e.target as HTMLInputElement).value
                )}
              class="border-input bg-background flex h-7 flex-1 rounded-lg border px-2 py-1 text-xs font-mono outline-none focus-visible:ring-2 focus-visible:ring-ring/50 placeholder:text-muted-foreground"
            />
            <datalist id="fb-model-suggestions-{i}">
              {#each providerModelsMap[fb.provider] ?? [] as m}
                <option value={m}></option>
              {/each}
            </datalist>
            <Button
              variant="ghost"
              size="icon-xs"
              onclick={() => removeFallback(i)}
            >
              <X />
            </Button>
          </div>
        {/each}
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-2.5">
        <div class="grid gap-1">
          <Label for="rkt">Required Key Tier</Label>
          <Input
            id="rkt"
            type="text"
            placeholder="(optional)"
            bind:value={formRequiredKeyTier}
          />
        </div>
        <div class="grid gap-1">
          <Label for="rktag">Required Key Tags</Label>
          <Input
            id="rktag"
            type="text"
            placeholder="tag1, tag2"
            bind:value={formRequiredKeyTags}
          />
        </div>
      </div>
    </Card.Content>
    <Card.Footer class="justify-end gap-1.5">
      <Button variant="outline" size="sm" onclick={cancelEdit}>Cancel</Button>
      <Button size="sm" onclick={onSave} disabled={saving}>
        <Save data-icon="inline-start" />{saving ? "Saving..." : "Save"}
      </Button>
    </Card.Footer>
  </Card.Root>
{/snippet}
